### ISSUE TITLE
Bug: uploading individuals with group_code and recipient_info does not create group & assignment

### ISSUE THREAD

**Issue by Shahzaibahmad97** [weilu/openimis-be_py#3]
Possibly related exception in django server:

```
django.db.backends: (0.004) UPDATE "individual_individualdatasourceupload" SET "isDeleted" = false, "Json_ext" = NULL, "DateCreated" = '2024-07-23T07:55:49.426455'::timestamp, "DateUpdated" = '2024-07-23T07:56:26.022501'::timestamp, "UserCreatedUUID" = '49dfef22-b232-4499-b603-afc4693ec1b4'::uuid, "UserUpdatedUUID" = '49dfef22-b232-4499-b603-afc4693ec1b4'::uuid, "version" = 6, "source_name" = 'tmpl1yoau912.csv', "source_type" = 'individual import', "status" = 'FAIL', "error" = '{"Task Resolve": "''Individual'' object has no attribute ''individuals_set''"}' WHERE "individual_individualdatasourceupload"."UUID" = '3424beb7-f559-4cb3-a04a-4d9e14134ce8'::uuid; args=(False, core.datetimes.ad_datetime.datetime(2024, 7, 23, 7, 55, 49, 426455), datetime.datetime(2024, 7, 23, 7, 56, 26, 22501), UUID('49dfef22-b232-4499-b603-afc4693ec1b4'), UUID('49dfef22-b232-4499-b603-afc4693ec1b4'), 6, 'tmpl1yoau912.csv', 'individual import', IndividualDataSourceUpload.Status.FAIL, <psycopg2._json.Json object at 0x1668255e0>, UUID('3424beb7-f559-4cb3-a04a-4d9e14134ce8')); alias=default
django.db.backends: (0.001) INSERT INTO "individual_historicalindividualdatasourceupload" ("UUID", "isDeleted", "Json_ext", "DateCreated", "DateUpdated", "version", "source_name", "source_type", "status", "error", "UserCreatedUUID", "UserUpdatedUUID", "history_date", "history_change_reason", "history_type", "history_user_id") VALUES ('3424beb7-f559-4cb3-a04a-4d9e14134ce8'::uuid, false, NULL, '2024-07-23T07:55:49.426455'::timestamp, '2024-07-23T07:56:26.022501'::timestamp, 6, 'tmpl1yoau912.csv', 'individual import', 'FAIL', '{"Task Resolve": "''Individual'' object has no attribute ''individuals_set''"}', '49dfef22-b232-4499-b603-afc4693ec1b4'::uuid, '49dfef22-b232-4499-b603-afc4693ec1b4'::uuid, '2024-07-23T07:56:26.028100'::timestamp, NULL, '~', NULL) RETURNING "individual_historicalindividualdatasourceupload"."history_id"; args=(UUID('3424beb7-f559-4cb3-a04a-4d9e14134ce8'), False, None, core.datetimes.ad_datetime.datetime(2024, 7, 23, 7, 55, 49, 426455), datetime.datetime(2024, 7, 23, 7, 56, 26, 22501), 6, 'tmpl1yoau912.csv', 'individual import', IndividualDataSourceUpload.Status.FAIL, <psycopg2._json.Json object at 0x166825730>, UUID('49dfef22-b232-4499-b603-afc4693ec1b4'), UUID('49dfef22-b232-4499-b603-afc4693ec1b4'), datetime.datetime(2024, 7, 23, 7, 56, 26, 28100), None, '~', None); alias=default
individual.signals.on_validation_import_valid_items: Error while executing on_task_complete_action for individual_validation.import_valid_items
Traceback (most recent call last):
  File "/Users/wlu4/workspace/openimis-be-individual_py/individual/signals/on_validation_import_valid_items.py", line 293, in on_task_complete_action
    IndividualItemsImportTaskCompletionEvent(
  File "/Users/wlu4/workspace/openimis-be-individual_py/individual/signals/on_validation_import_valid_items.py", line 255, in run_workflow
    self._clean_json_ext()
  File "/Users/wlu4/workspace/openimis-be-individual_py/individual/signals/on_validation_import_valid_items.py", line 161, in _clean_json_ext
    individual.save(username=self.user.username)
  File "/Users/wlu4/workspace/openimis-be-core_py/core/models/history_model.py", line 91, in save
    return super(HistoryModel, self).save(*args, **kwargs)
  File "/Users/wlu4/Envs/coremis/lib/python3.8/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/wlu4/Envs/coremis/lib/python3.8/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/Users/wlu4/Envs/coremis/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/Users/wlu4/Envs/coremis/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/wlu4/Envs/coremis/lib/python3.8/site-packages/django_opensearch_dsl/signals.py", line 54, in handle_save
    registry.update_related(instance)
  File "/Users/wlu4/Envs/coremis/lib/python3.8/site-packages/django_opensearch_dsl/registries.py", line 110, in update_related
    related = doc_instance.get_instances_from_related(instance)
  File "/Users/wlu4/workspace/openimis-be-individual_py/individual/documents.py", line 84, in get_instances_from_related
    return related_instance.individuals_set.all()
AttributeError: 'Individual' object has no attribute 'individuals_set'
```

**Comment by weilu** [comment]
Related PR: https://github.com/openimis/openimis-be-individual_py/pull/120

@Shahzaibahmad97 going forward, please make PRs from a none-default branch (in this case develop) so they can be linked to the project story's "Development" section
